config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  namespace :api do
    namespace :v1 do
      resources :contract_types, only: [:index]
      resources :quotes, only: [:create, :update, :show] do
        member do
          patch :reset
          get :generate_file
        end
        resources :quote_items, only: [:update, :index] do
          collection do
            post :create_from_item
            post :create_from_category
            delete :destroy_selected
          end
          post :duplicate, on: :member
          resource :note, only: [:destroy] do
            post :upsert
          end
        end
      end
      resources :selectable_options, only: [:index]
      resource :setting, only: [:show]
      resources :customers, only: [:index] do
        post :upsert, on: :collection
      end
    end
  end

  get "up" => "rails/health#show", as: :rails_health_check

  root 'homepage#index'
  get "*path", to: "homepage#index", constraints: ->(req) { !req.xhr? && req.format.html? }
end

app/models/setting.rb
class Setting < ApplicationRecord
  has_one_attached :logo_light_background
  has_one_attached :logo_dark_background
  has_one_attached :word_header_document_logo

  MAX_IMAGE_SIZE = 1.megabyte
  ALLOWED_IMAGE_TYPES = %w[image/jpeg image/png].freeze

  validate :only_one_setting_allowed
  validates :logo_light_background, file_size: { max: MAX_IMAGE_SIZE },
                                    file_content_type: { allowed_types: ALLOWED_IMAGE_TYPES },
                                    if: -> { logo_light_background.attached? }
  validates :logo_dark_background, file_size: { max: MAX_IMAGE_SIZE },
                                   file_content_type: { allowed_types: ALLOWED_IMAGE_TYPES },
                                   if: -> { logo_dark_background.attached? }
  validates :word_header_document_logo, file_size: { max: MAX_IMAGE_SIZE },
                                        file_content_type: { allowed_types: ALLOWED_IMAGE_TYPES },
                                        if: -> { word_header_document_logo.attached? }

  # Returns the singleton setting instance, creates it if it doesn't exist
  def self.current
    return first if exists?

    # fetch colors from SCSS file
    primary, secondary, blue_light, blue_sky, light = BrandColorParser.default_colors

    # build style
    style = BrandColorBuilder.new(primary, secondary, blue_light, blue_sky, light).build_css

    create!(style: style)
  end

  def favicon_url
    if logo_light_background.attached?
      variant = logo_light_background.variant(resize_and_pad: [64, 64]).processed
      Rails.application.routes.url_helpers.rails_representation_url(variant, only_path: true,
                                                                             version: Time.current.to_i)
    else
      '/favicon.png'
    end
  end

  private

  def only_one_setting_allowed
    return unless Setting.where.not(id: id).exists?

    errors.add(:base, "Only one instance of Setting is allowed.")
  end
end

app/controllers/api/v1/settings_controller.rb
module Api
  module V1
    class SettingsController < ApplicationController
      skip_before_action :authenticate_user!

      def show
        setting = Setting.current

        render json: SettingSerializer.new(setting).serializable_hash, status: :ok
      end
    end
  end
end

app/helpers/api/v1/settings_helper.rb
module Api
  module V1
    module SettingsHelper
      def current_setting
        Setting.current
      end
    end
  end
end

app/views/admin/setting/_display_images.html.erb
<div class="panel">
  <h3>Display & Control Images</h3>
  <div class="panel_contents">
    <div class="columns">
      <div class="column" style="width: 32.0%; margin-right: 2%;">
        <h3>Logo for light background:</h3>
        <% if setting.logo_light_background.attached? && setting.logo_light_background.persisted? %>
          <%= image_tag setting.logo_light_background, style: 'margin-bottom: 10px; object-fit: contain; width: 200px; max-height: 200px;' %>
          <%= button_to 'Remove', admin_setting_remove_image_path(type: 'logo_light_background'), method: :delete %>
        <% else %>
          <p>Not yet uploaded.</p>
        <% end %>
      </div>
      <div class="column" style="width: 32.0%; margin-right: 2%;">
        <h3>Logo for dark background:</h3>
        <% if setting.logo_dark_background.attached? && setting.logo_dark_background.persisted? %>
          <%= image_tag setting.logo_dark_background, style: 'margin-bottom: 10px; object-fit: contain; width: 200px; max-height: 200px;' %>
          <%= button_to 'Remove', admin_setting_remove_image_path(type: 'logo_dark_background'), method: :delete %>
        <% else %>
          <p>Not yet uploaded.</p>
        <% end %>
      </div>
      <div class="column" style="width: 32.0%;">
        <h3>Word Header Document Logo:</h3>
        <% if setting.word_header_document_logo.attached? && setting.word_header_document_logo.persisted? %>
          <%= image_tag setting.word_header_document_logo, style: 'margin-bottom: 10px; object-fit: contain; width: 200px; max-height: 200px;' %>
          <%= button_to 'Remove', admin_setting_remove_image_path(type: 'word_header_document_logo'), method: :delete %>
        <% else %>
          <p>Not yet uploaded.</p>
        <% end %>
      </div>
      <div style="clear:both;"></div>
    </div>
  </div>
</div>

app/views/admin/setting/_display_logo.html.erb
<div class="panel">
  <h3>Display & Control Images</h3>
  <div class="panel_contents">
    <div class="columns">

      <div class="column" style="width: 32.0%; margin-right: 2%;">
        <% if setting.logo.attached? %>
          <%= image_tag setting.logo, style: 'margin-bottom: 10px; object-fit: contain; width: 200px; max-height: 200px;' %>
          <%= button_to 'Remove logo', admin_setting_remove_image_path(image: 'logo'), method: :delete %>
        <% else %>
          Logo not uploaded
        <% end %>
      </div>

      <div class="column" style="width: 32.0%; margin-right: 2%;">
        <% if setting.login_background.attached? %>
          <%= image_tag setting.login_background, style: 'margin-bottom: 10px; object-fit: contain; width: 200px; max-height: 200px;' %>
          <%= button_to 'Remove login background', admin_setting_remove_image_path(image: 'login_background'), method: :delete %>
        <% else %>
          Login background not uploaded
        <% end %>
      </div>

      <div class="column" style="width: 32.0%;">
        <% if setting.app_background.attached? %>
          <%= image_tag setting.app_background, style: 'margin-bottom: 10px; object-fit: contain; width: 200px; max-height: 200px;' %>
          <%= button_to 'Remove app background', admin_setting_remove_image_path(image: 'app_background'), method: :delete %>
        <% else %>
          App background not uploaded
        <% end %>
      </div>

      <div style="clear:both;"></div>
    </div>
  </div>
</div>

app/views/admin/setting/_form.html.erb
<%= form_with model: setting, url: admin_setting_update_path, method: :put, html: { multipart: true } do |f| %>
  <fieldset class="inputs">
    <legend class="fieldset-title"><span>Word Document</span></legend>
    <ol>
      <li class="file input optional">
        <%= f.label "Header logo", class: 'label', for: 'setting_word_header_document_logo' %>
        <%= f.file_field :word_header_document_logo, accept: Setting::ALLOWED_IMAGE_TYPES.join(',') %>
        <% if setting.errors[:word_header_document_logo].present? %>
          <p class="inline-errors"><%= setting.errors.full_messages_for(:word_header_document_logo).to_sentence %></p>
        <% end %>
      </li>
    </ol>
  </fieldset>

  <fieldset class="inputs">
    <legend class="fieldset-title"><span>App</span></legend>
    <ol>
      <li class="file input optional">
        <%= f.label 'Logo for light background', class: 'label', for:'setting_logo_light_background' %>
        <%= f.file_field :logo_light_background, accept: Setting::ALLOWED_IMAGE_TYPES.join(',') %>
        <% if setting.errors[:logo_light_background].present? %>
          <p class="inline-errors"><%= setting.errors.full_messages_for(:logo_light_background).to_sentence %></p>
        <% end %>
      </li>
      <li class="file input optional">
        <%= f.label "Logo for dark background", class: 'label', for:'setting_logo_dark_background' %>
        <%= f.file_field :logo_dark_background, accept: Setting::ALLOWED_IMAGE_TYPES.join(',') %>
        <% if setting.errors[:logo_dark_background].present? %>
          <p class="inline-errors"><%= setting.errors.full_messages_for(:logo_dark_background).to_sentence %></p>
        <% end %>
      </li>
      <li class="color input optional">
        <%= f.label :primary_color, class: 'label' %>
        <%= f.color_field :primary_color, value: style.primary_color %>
      </li>
      <li class="color input optional">
        <%= f.label :secondary_color, class: 'label' %>
        <%= f.color_field :secondary_color, value: style.secondary_color %>
      </li>
      <li class="color input optional">
        <%= f.label :blue_light_color, class: 'label' %>
        <%= f.color_field :blue_light_color, value: style.blue_light_color %>
      </li>
      <li class="color input optional">
        <%= f.label :blue_sky_color, class: 'label' %>
        <%= f.color_field :blue_sky_color, value: style.blue_sky_color %>
      </li>
      <li class="color input optional">
        <%= f.label :light_color, class: 'label' %>
        <%= f.color_field :light_color, value: style.light_color %>
      </li>
    </ol>
  </fieldset>
  <%= f.submit 'Save' %>
<% end %>
<%= button_to 'Reset to Default', admin_setting_reset_path,
              method: :patch,
              'data-confirm': "Are you sure you want to reset the setting to default?",
              style: 'margin-top: 10px;' %>